import { FC, useContext, useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import {
  WalletAuthContext,
  WalletAuthContextType,
} from "../../contexts/WalletAuthWrapper";
import { OrgResponse } from "../../utils/ChainAidContract";

const Organization: FC = () => {
  const { contract } = useContext(WalletAuthContext) as WalletAuthContextType;

  const [orgData, setOrgData] = useState<OrgResponse[] | null>();

  useEffect(() => {
    async function getOrgs() {
      let data = await contract?.getAllOrgs();
      setOrgData(data);
    }

    getOrgs();
  }, [contract]);

  return (
    <>
      <Head>
        <title>Organization | ChainAid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl">All Organizations</h1>

      <div className="flex flex-col mt-20">
        {orgData?.map((org, i) => (
          <div key={"org" + i} className="text-2xl py-2">
            {org[0]}
          </div>
        ))}
      </div>
    </>
  );
};

export default Organization;
