import { FC, FormEvent, useContext, useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import { ethers } from "ethers";
import RingSpinner from "../../components/loaders/ringSpinner";
import {
  WalletAuthContext,
  WalletAuthContextType,
} from "../../contexts/WalletAuthWrapper";

const Organization: FC = () => {
  const [name, setName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [contact, setContact] = useState<string>("");
  const [website, setWebsite] = useState<string>("");
  const [value, setValue] = useState<string>("");

  const [loading, setLoading] = useState(false);

  const { contract } = useContext(WalletAuthContext) as WalletAuthContextType;

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setLoading(true);
    console.log("hi");

    if (contract) {
      await contract.addOrg(name, email, contact, website, {
        value: ethers.utils.parseEther("0.1"),
      });
    }

    setLoading(false);
  };
  return (
    <>
      {/* <Head>
        <title>New Organization | ChainAid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <div className="w-full content-center">
        <form
          className="bg-slate-400 shadow-md p-10 max-w-xl mx-auto flex flex-col items-center text-black"
          onSubmit={handleSubmit}
        >
          <h1 className="mb-10 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-3xl dark:text-white">
            Register as Organization
          </h1>
          <div className="mb-6 w-full">
            <input
              id="name"
              type="text"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
              }}
              placeholder="Name"
              required
              className="outline-none font-medium w-full py-2 px-3 rounded-md border border-black border-opacity-20 focus:shadow focus:ring-1 focus:ring-black"
              maxLength={100}
            />
          </div>
          <div className="mb-6 w-full">
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
              }}
              placeholder="Email"
              required
              className="outline-none font-medium w-full py-2 px-3 rounded-md border border-black border-opacity-20 focus:shadow focus:ring-1 focus:ring-black"
              maxLength={100}
            />
          </div>
          <div className="mb-6 w-full">
            <input
              id="contact"
              type="text"
              value={contact}
              onChange={(e) => {
                setContact(e.target.value);
              }}
              placeholder="Contact"
              required
              className="outline-none font-medium w-full py-2 px-3 rounded-md border border-black border-opacity-20 focus:shadow focus:ring-1 focus:ring-black"
              maxLength={100}
            />
          </div>
          <div className="mb-6 w-full">
            <input
              id="website"
              type="text"
              value={website}
              onChange={(e) => {
                setWebsite(e.target.value);
              }}
              placeholder="Website"
              required
              className="outline-none font-medium w-full py-2 px-3 rounded-md border border-black border-opacity-20 focus:shadow focus:ring-1 focus:ring-black"
              maxLength={100}
            />
          </div>
          <div className="mb-6 w-full">
            <input
              id="value"
              type="number"
              value={value}
              onChange={(e) => {
                setValue(e.target.value);
              }}
              placeholder="Deposit value"
              required
              className="outline-none font-medium w-full py-2 px-3 rounded-md border border-black border-opacity-20 focus:shadow focus:ring-1 focus:ring-black"
              maxLength={100}
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className={`mt-3 flex items-center bg-black hover:bg-opacity-70 px-3 py-2 text-white rounded-md ${
              loading ? "bg-opacity-70" : ""
            }`}
          >
            {loading ? (
              <div className="ml-2">
                <RingSpinner width={20} color="white" />
              </div>
            ) : (
              <div>Create</div>
            )}
          </button>
        </form>
      </div>
    </>
  );
};

export default Organization;
