import Head from "next/head";
import React, { useState, useEffect } from "react";
import Axios from "axios";
import baseUrl from "../../components/baseUrl";

function list() {
  const [requests, setRequests] = useState([]);

  useEffect(() => {
    Axios.get(`${baseUrl}/api/get`).then((res) => setRequests(res.data)).catch(err=>alert("Could not fetch data"));
  }, []);

  return (
    <>
      {requests.length == 0 ? (
        <div>Loading...</div>
      ) : (
        <div>
          <Head>
            <title>ChainAid | Mentor</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>Helloo</main>
        </div>
      )}
    </>
  );
}

export default list;
